language: python
dist: xenial
python:
- "2.7"
- "3.5"
- "3.6"
- "3.7"
install:
  - pip install -r requirements.txt
  - npm install -g pa11y
script:
  - pytest
  - python setup.py install
  - adr-viewer
  - pa11y ./index.html --config pa11y.json